{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOs8LCq7urkUeZ1Jyl7V1A9",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/dartatri/unie/blob/main/binominal_tree.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 10,
      "metadata": {
        "id": "xOvVFzzQbIGw"
      },
      "outputs": [],
      "source": [
        "import numpy as np\n",
        "from math import log, sqrt, exp\n",
        "from scipy.stats import norm\n",
        "\n",
        "def jarrow_rudd_params(r, sigma, dt, q=0.0):\n",
        "    \"\"\"\n",
        "    Parámetros u, d, p del esquema Jarrow–Rudd con p=0.5.\n",
        "    Ecuaciones:\n",
        "        e^{R dt} = (u + d)/2\n",
        "        sigma*sqrt(dt) = (ln u - ln d)/2\n",
        "        donde R = r - q\n",
        "        => u = e^{R dt} e^{+a} * [ 2/(e^{a} + e^{-a}) ]\n",
        "           d = e^{R dt} e^{-a} * [ 2/(e^{a} + e^{-a}) ]\n",
        "           con a = sigma*sqrt(dt)\n",
        "    \"\"\"\n",
        "    R = r - q\n",
        "    a = sigma * np.sqrt(dt)\n",
        "    C = 2.0 / (np.exp(a) + np.exp(-a))  # = 1/cosh(a)\n",
        "    u = np.exp(R * dt) * np.exp(+a) * C\n",
        "    d = np.exp(R * dt) * np.exp(-a) * C\n",
        "    p = 0.5\n",
        "    return u, d, p\n",
        "\n",
        "def binomial_tree_prices(S0, u, d, N):\n",
        "    \"\"\"\n",
        "    Devuelve una matriz (N+1)x(N+1) con precios del subyacente.\n",
        "    Columna i = paso i; fila j = i con j bajadas (j=0..i).\n",
        "    \"\"\"\n",
        "    S = np.zeros((N + 1, N + 1))\n",
        "    S[0, 0] = S0\n",
        "    for i in range(1, N + 1):\n",
        "        # nivel superior (todas subidas hasta aquí)\n",
        "        S[0, i] = S[0, i-1] * u\n",
        "        # resto de nodos\n",
        "        for j in range(1, i + 1):\n",
        "            S[j, i] = S[j-1, i-1] * d\n",
        "    return S\n",
        "\n",
        "def option_payoff(S, K, option_type=\"call\"):\n",
        "    if option_type.lower() == \"call\":\n",
        "        return np.maximum(S - K, 0.0)\n",
        "    elif option_type.lower() == \"put\":\n",
        "        return np.maximum(K - S, 0.0)\n",
        "    else:\n",
        "        raise ValueError(\"option_type debe ser 'call' o 'put'.\")\n",
        "\n",
        "def price_option_jarrow_rudd(\n",
        "    S0, K, r, sigma, T, N,\n",
        "    option_type=\"call\",\n",
        "    exercise=\"european\",\n",
        "    q=0.0\n",
        "):\n",
        "    \"\"\"\n",
        "    Valora una opción con árbol binomial Jarrow–Rudd (p=0.5).\n",
        "\n",
        "    Parámetros:\n",
        "        S0: precio spot\n",
        "        K: strike\n",
        "        r: tipo libre de riesgo (cont. compuesto)\n",
        "        sigma: volatilidad anual\n",
        "        T: vencimiento (en años)\n",
        "        N: número de pasos del árbol\n",
        "        option_type: 'call' o 'put'\n",
        "        exercise: 'european' o 'american'\n",
        "        q: dividend yield continuo (por defecto 0)\n",
        "\n",
        "    Devuelve:\n",
        "        precio, y un dict con (u, d, p).\n",
        "    \"\"\"\n",
        "    dt = T / N\n",
        "    u, d, p = jarrow_rudd_params(r, sigma, dt, q=q)\n",
        "    disc = np.exp(-r * dt)\n",
        "\n",
        "    # Árbol de precios del subyacente\n",
        "    S = binomial_tree_prices(S0, u, d, N)\n",
        "\n",
        "    # Payoff terminal\n",
        "    V = option_payoff(S[:N+1, N], K, option_type=option_type)\n",
        "\n",
        "    # Backward induction\n",
        "    american = (exercise.lower() == \"american\")\n",
        "    for i in range(N - 1, -1, -1):\n",
        "        V = disc * (p * V[:i+1] + (1 - p) * V[1:i+2])\n",
        "        if american:\n",
        "            # Valor por ejercicio anticipado\n",
        "            intrinsic = option_payoff(S[:i+1, i], K, option_type=option_type)\n",
        "            V = np.maximum(V, intrinsic)\n",
        "\n",
        "    price = float(V[0])\n",
        "    params = {\"u\": u, \"d\": d, \"p\": p, \"dt\": dt}\n",
        "    return price, params\n",
        "\n",
        "def black_scholes_with_q(S0, K, r, q, sigma, T, option_type=\"call\"):\n",
        "    \"\"\"\n",
        "    Calcula el precio de una opción europea con dividend yield continuo q\n",
        "    usando el modelo de Black–Scholes.\n",
        "\n",
        "    Parámetros:\n",
        "        S0: precio actual del activo\n",
        "        K: precio de ejercicio\n",
        "        r: tipo libre de riesgo (continuamente compuesto)\n",
        "        q: tasa de dividendos continuos\n",
        "        sigma: volatilidad anual\n",
        "        T: tiempo hasta vencimiento (en años)\n",
        "        option_type: 'call' o 'put'\n",
        "    \"\"\"\n",
        "    # Manejo de casos límite\n",
        "    if T <= 0 or sigma <= 0:\n",
        "        if option_type.lower() == \"call\":\n",
        "            return max(S0 * exp(-q*T) - K * exp(-r*T), 0.0)\n",
        "        else:\n",
        "            return max(K * exp(-r*T) - S0 * exp(-q*T), 0.0)\n",
        "\n",
        "    d1 = (log(S0 / K) + (r - q + 0.5 * sigma**2) * T) / (sigma * sqrt(T))\n",
        "    d2 = d1 - sigma * sqrt(T)\n",
        "\n",
        "    if option_type.lower() == \"call\":\n",
        "        price = S0 * exp(-q * T) * norm.cdf(d1) - K * exp(-r * T) * norm.cdf(d2)\n",
        "    elif option_type.lower() == \"put\":\n",
        "        price = K * exp(-r * T) * norm.cdf(-d2) - S0 * exp(-q * T) * norm.cdf(-d1)\n",
        "    else:\n",
        "        raise ValueError(\"option_type debe ser 'call' o 'put'.\")\n",
        "\n",
        "    return price\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "b3av489do06m"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}